collections:
    portfolio_entries:
        output: true
        permalink: /portfolio/:title/

exclude: ["private", "artwork", "node_modules", "gulpfile.js", "*.log", "package.json"]

keep_files: ["images", "protected"]

images_path: "/images"

title: "Egle Strockyte - Digital Product Designer"
description: "I'm Egle Strockyte a Los Angeles based digital product designer"
