collections:
    portfolio_entries:
        output: true
        permalink: /portfolio/:path/

exclude: ["artwork", "node_modules", "gulpfile.js", "*.log", "package.json"]

keep_files: ["images"]

images_path: "/images"
